### ISSUE TITLE
Support label creation via callback function

### ISSUE THREAD

**Issue by olaf-otto** [kevinschaul/d3-star-plot#7]
Currently, the star plot allows specifying labels as an array of string values. However, it would be great if the labels could also be provided via a callback function, similar to the way the title is created. Then, one could efficiently add data-based labels, e.g. in order to display the axis value or unit in the label, like so:

    // d: datum, i: property index
    .labels(function(d, i) {
         return labels[i] + ": " + d[properties[i]].toFixed(1);
     })

**Comment by olaf-otto** [comment]
Pull request: https://github.com/kevinschaul/d3-star-plot/pull/8

**Comment by kevinschaul** [comment]
ebad0e2d1ee5960377f7fda678eaf45581de2978
